package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Alloy generated by hbm2java
 */
public class Alloy  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set parts = new HashSet(0);

    public Alloy() {
    }

	
    public Alloy(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Alloy(BigDecimal id, String name, Set parts) {
       this.id = id;
       this.name = name;
       this.parts = parts;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getParts() {
        return this.parts;
    }
    
    public void setParts(Set parts) {
        this.parts = parts;
    }




}


