package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Dep generated by hbm2java
 */
public class Dep  implements java.io.Serializable {


     private BigDecimal id;
     private TypeDep typeDep;
     private BigDecimal num;
     private Set stages = new HashSet(0);

    public Dep() {
    }

	
    public Dep(BigDecimal id, TypeDep typeDep, BigDecimal num) {
        this.id = id;
        this.typeDep = typeDep;
        this.num = num;
    }
    public Dep(BigDecimal id, TypeDep typeDep, BigDecimal num, Set stages) {
       this.id = id;
       this.typeDep = typeDep;
       this.num = num;
       this.stages = stages;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public TypeDep getTypeDep() {
        return this.typeDep;
    }
    
    public void setTypeDep(TypeDep typeDep) {
        this.typeDep = typeDep;
    }
    public BigDecimal getNum() {
        return this.num;
    }
    
    public void setNum(BigDecimal num) {
        this.num = num;
    }
    public Set getStages() {
        return this.stages;
    }
    
    public void setStages(Set stages) {
        this.stages = stages;
    }




}


