package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Part generated by hbm2java
 */
public class Part  implements java.io.Serializable {


     private BigDecimal id;
     private Alloy alloy;
     private String name;
     private BigDecimal cost;
     private String blnum;
     private Set stages = new HashSet(0);

    public Part() {
    }

	
    public Part(BigDecimal id, Alloy alloy, String name, BigDecimal cost, String blnum) {
        this.id = id;
        this.alloy = alloy;
        this.name = name;
        this.cost = cost;
        this.blnum = blnum;
    }
    public Part(BigDecimal id, Alloy alloy, String name, BigDecimal cost, String blnum, Set stages) {
       this.id = id;
       this.alloy = alloy;
       this.name = name;
       this.cost = cost;
       this.blnum = blnum;
       this.stages = stages;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Alloy getAlloy() {
        return this.alloy;
    }
    
    public void setAlloy(Alloy alloy) {
        this.alloy = alloy;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public String getBlnum() {
        return this.blnum;
    }
    
    public void setBlnum(String blnum) {
        this.blnum = blnum;
    }
    public Set getStages() {
        return this.stages;
    }
    
    public void setStages(Set stages) {
        this.stages = stages;
    }




}


