package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage  implements java.io.Serializable {


     private BigDecimal id;
     private Part part;
     private Stage stageByIdNext;
     private Surface surface;
     private Stage stageByIdPrev;
     private Dep dep;
     private Set stagesForIdNext = new HashSet(0);
     private Set stagesForIdPrev = new HashSet(0);

    public Stage() {
    }

	
    public Stage(BigDecimal id, Part part, Stage stageByIdNext, Surface surface, Stage stageByIdPrev, Dep dep) {
        this.id = id;
        this.part = part;
        this.stageByIdNext = stageByIdNext;
        this.surface = surface;
        this.stageByIdPrev = stageByIdPrev;
        this.dep = dep;
    }
    public Stage(BigDecimal id, Part part, Stage stageByIdNext, Surface surface, Stage stageByIdPrev, Dep dep, Set stagesForIdNext, Set stagesForIdPrev) {
       this.id = id;
       this.part = part;
       this.stageByIdNext = stageByIdNext;
       this.surface = surface;
       this.stageByIdPrev = stageByIdPrev;
       this.dep = dep;
       this.stagesForIdNext = stagesForIdNext;
       this.stagesForIdPrev = stagesForIdPrev;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Part getPart() {
        return this.part;
    }
    
    public void setPart(Part part) {
        this.part = part;
    }
    public Stage getStageByIdNext() {
        return this.stageByIdNext;
    }
    
    public void setStageByIdNext(Stage stageByIdNext) {
        this.stageByIdNext = stageByIdNext;
    }
    public Surface getSurface() {
        return this.surface;
    }
    
    public void setSurface(Surface surface) {
        this.surface = surface;
    }
    public Stage getStageByIdPrev() {
        return this.stageByIdPrev;
    }
    
    public void setStageByIdPrev(Stage stageByIdPrev) {
        this.stageByIdPrev = stageByIdPrev;
    }
    public Dep getDep() {
        return this.dep;
    }
    
    public void setDep(Dep dep) {
        this.dep = dep;
    }
    public Set getStagesForIdNext() {
        return this.stagesForIdNext;
    }
    
    public void setStagesForIdNext(Set stagesForIdNext) {
        this.stagesForIdNext = stagesForIdNext;
    }
    public Set getStagesForIdPrev() {
        return this.stagesForIdPrev;
    }
    
    public void setStagesForIdPrev(Set stagesForIdPrev) {
        this.stagesForIdPrev = stagesForIdPrev;
    }




}


