package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Surface generated by hbm2java
 */
public class Surface  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set stages = new HashSet(0);

    public Surface() {
    }

	
    public Surface(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public Surface(BigDecimal id, String name, Set stages) {
       this.id = id;
       this.name = name;
       this.stages = stages;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStages() {
        return this.stages;
    }
    
    public void setStages(Set stages) {
        this.stages = stages;
    }




}


