package h.entity;
// Generated Feb 11, 2014 9:30:18 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TypeDep generated by hbm2java
 */
public class TypeDep  implements java.io.Serializable {


     private BigDecimal id;
     private String name;
     private Set deps = new HashSet(0);

    public TypeDep() {
    }

	
    public TypeDep(BigDecimal id, String name) {
        this.id = id;
        this.name = name;
    }
    public TypeDep(BigDecimal id, String name, Set deps) {
       this.id = id;
       this.name = name;
       this.deps = deps;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDeps() {
        return this.deps;
    }
    
    public void setDeps(Set deps) {
        this.deps = deps;
    }




}


